tools/gcc/git(41):ERROR:105: Unable to locate a modulefile for 'tools/gcc/git/2.8.2'
              total        used        free      shared  buff/cache   available
Mem:         191862       10817       12052         267      168991      180042
Swap:          8191         878        7313
Wed Jun  2 15:28:40 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:1A:00.0 Off |                    0 |
| N/A   63C    P0   196W / 300W |   1570MiB / 16160MiB |     88%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:1C:00.0 Off |                    0 |
| N/A   42C    P0   109W / 300W |   2226MiB / 16160MiB |     38%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:1D:00.0 Off |                    0 |
| N/A   33C    P0    54W / 300W |      0MiB / 16160MiB |      0%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:1E:00.0 Off |                    0 |
| N/A   39C    P0    78W / 300W |    424MiB / 16160MiB |     23%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    147103      C   pmemd.cuda                       1567MiB |
|    1   N/A  N/A    142828      C   python                           2223MiB |
|    3   N/A  N/A    143745      C   gmx                               421MiB |
+-----------------------------------------------------------------------------+
2021-06-02 15:28:45.586510: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-06-02 15:29:04.309830: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-02 15:29:04.316265: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-06-02 15:29:05.498275: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:1d:00.0 name: Tesla V100-SXM2-16GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 15.78GiB deviceMemoryBandwidth: 836.37GiB/s
2021-06-02 15:29:05.498426: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-06-02 15:29:05.540369: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2021-06-02 15:29:05.540540: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2021-06-02 15:29:05.682516: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-06-02 15:29:05.694864: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-06-02 15:29:05.775705: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-06-02 15:29:05.792510: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2021-06-02 15:29:05.901966: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2021-06-02 15:29:05.904566: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-06-02 15:29:05.905760: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-02 15:29:05.908046: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:1d:00.0 name: Tesla V100-SXM2-16GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 15.78GiB deviceMemoryBandwidth: 836.37GiB/s
2021-06-02 15:29:05.908096: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-06-02 15:29:05.908153: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2021-06-02 15:29:05.908174: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2021-06-02 15:29:05.908193: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-06-02 15:29:05.908213: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-06-02 15:29:05.908232: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-06-02 15:29:05.908250: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2021-06-02 15:29:05.908270: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2021-06-02 15:29:05.910481: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-06-02 15:29:05.913844: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-06-02 15:29:13.004573: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-06-02 15:29:13.005061: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2021-06-02 15:29:13.005093: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2021-06-02 15:29:13.011971: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14761 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:1d:00.0, compute capability: 7.0)
2021-06-02 15:29:13.015230: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-02 15:29:14.615243: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-06-02 15:29:14.619463: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2100000000 Hz
WARNING:tensorflow:AutoGraph could not transform <function custom_mse at 0x2af81eb0f8b0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
MODEL NAME = previous_arc_but_relu_before_BN_step1
Epoch 1/10
2021-06-02 15:29:18.141919: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2021-06-02 15:29:20.942717: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2021-06-02 15:29:28.565933: W tensorflow/stream_executor/gpu/asm_compiler.cc:63] Running ptxas --version returned 256
2021-06-02 15:29:28.709307: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: ptxas exited with non-zero error code 256, output: 
Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once.
300/300 - 929s - loss: 1.2689 - presence_loss: 0.6821 - coordinates_loss: 0.5867 - presence_accuracy: 0.6242
Epoch 2/10
300/300 - 869s - loss: 0.2776 - presence_loss: 0.2519 - coordinates_loss: 0.0257 - presence_accuracy: 0.9047
Epoch 3/10
300/300 - 844s - loss: 0.1432 - presence_loss: 0.1274 - coordinates_loss: 0.0159 - presence_accuracy: 0.9565
Epoch 4/10
300/300 - 845s - loss: 0.1122 - presence_loss: 0.0993 - coordinates_loss: 0.0129 - presence_accuracy: 0.9670
Epoch 5/10
300/300 - 839s - loss: 0.0946 - presence_loss: 0.0796 - coordinates_loss: 0.0151 - presence_accuracy: 0.9757
Epoch 6/10
300/300 - 768s - loss: 0.1099 - presence_loss: 0.0850 - coordinates_loss: 0.0249 - presence_accuracy: 0.9728
2021-06-02 16:54:37.144239: W tensorflow/core/framework/op_kernel.cc:1751] Unknown: LinAlgError: Singular matrix
Traceback (most recent call last):

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 891, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/mnt/jw01-aruk-home01/projects/ra_challenge/hestia/Hestia_imeche_vision_challenge/NN_recognition_train/dataset/train_generator.py", line 65, in train_generator
    X, coords, letter, colour = stitch_random_square(random.choice(list_of_grass_images))

  File "/mnt/jw01-aruk-home01/projects/ra_challenge/hestia/Hestia_imeche_vision_challenge/NN_recognition_train/dataset/square_generation.py", line 111, in stitch_random_square
    grass_img = paste_square([(int(A_X), int(A_Y)), (int(B_X), int(B_Y)), (int(C_X), int(C_Y)), (int(D_X), int(D_Y))], grass_img, square_img)

  File "/mnt/jw01-aruk-home01/projects/ra_challenge/hestia/Hestia_imeche_vision_challenge/NN_recognition_train/dataset/square_generation.py", line 69, in paste_square
    coeffs = find_coeffs(

  File "/mnt/jw01-aruk-home01/projects/ra_challenge/hestia/Hestia_imeche_vision_challenge/NN_recognition_train/dataset/square_generation.py", line 66, in find_coeffs
    res = np.dot(np.linalg.inv(A.T * A) * A.T, B)

  File "<__array_function__ internals>", line 5, in inv

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 547, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 97, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")

numpy.linalg.LinAlgError: Singular matrix


Epoch 7/10
Traceback (most recent call last):
  File "train.py", line 24, in <module>
    train_this(model_name)
  File "/mnt/jw01-aruk-home01/projects/ra_challenge/hestia/Hestia_imeche_vision_challenge/NN_recognition_train/model/mobile_net.py", line 92, in train_this
    model.fit(tf_data, epochs = 10, verbose = 2, steps_per_epoch = 300)
  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 855, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown:  LinAlgError: Singular matrix
Traceback (most recent call last):

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 891, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/mnt/jw01-aruk-home01/projects/ra_challenge/hestia/Hestia_imeche_vision_challenge/NN_recognition_train/dataset/train_generator.py", line 65, in train_generator
    X, coords, letter, colour = stitch_random_square(random.choice(list_of_grass_images))

  File "/mnt/jw01-aruk-home01/projects/ra_challenge/hestia/Hestia_imeche_vision_challenge/NN_recognition_train/dataset/square_generation.py", line 111, in stitch_random_square
    grass_img = paste_square([(int(A_X), int(A_Y)), (int(B_X), int(B_Y)), (int(C_X), int(C_Y)), (int(D_X), int(D_Y))], grass_img, square_img)

  File "/mnt/jw01-aruk-home01/projects/ra_challenge/hestia/Hestia_imeche_vision_challenge/NN_recognition_train/dataset/square_generation.py", line 69, in paste_square
    coeffs = find_coeffs(

  File "/mnt/jw01-aruk-home01/projects/ra_challenge/hestia/Hestia_imeche_vision_challenge/NN_recognition_train/dataset/square_generation.py", line 66, in find_coeffs
    res = np.dot(np.linalg.inv(A.T * A) * A.T, B)

  File "<__array_function__ internals>", line 5, in inv

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 547, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 97, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")

numpy.linalg.LinAlgError: Singular matrix


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]
  (1) Unknown:  LinAlgError: Singular matrix
Traceback (most recent call last):

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 891, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/mnt/jw01-aruk-home01/projects/ra_challenge/hestia/Hestia_imeche_vision_challenge/NN_recognition_train/dataset/train_generator.py", line 65, in train_generator
    X, coords, letter, colour = stitch_random_square(random.choice(list_of_grass_images))

  File "/mnt/jw01-aruk-home01/projects/ra_challenge/hestia/Hestia_imeche_vision_challenge/NN_recognition_train/dataset/square_generation.py", line 111, in stitch_random_square
    grass_img = paste_square([(int(A_X), int(A_Y)), (int(B_X), int(B_Y)), (int(C_X), int(C_Y)), (int(D_X), int(D_Y))], grass_img, square_img)

  File "/mnt/jw01-aruk-home01/projects/ra_challenge/hestia/Hestia_imeche_vision_challenge/NN_recognition_train/dataset/square_generation.py", line 69, in paste_square
    coeffs = find_coeffs(

  File "/mnt/jw01-aruk-home01/projects/ra_challenge/hestia/Hestia_imeche_vision_challenge/NN_recognition_train/dataset/square_generation.py", line 66, in find_coeffs
    res = np.dot(np.linalg.inv(A.T * A) * A.T, B)

  File "<__array_function__ internals>", line 5, in inv

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 547, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 97, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")

numpy.linalg.LinAlgError: Singular matrix


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_2]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_8686]

Function call stack:
train_function -> train_function

