tools/gcc/git(41):ERROR:105: Unable to locate a modulefile for 'tools/gcc/git/2.8.2'
              total        used        free      shared  buff/cache   available
Mem:         128677       10006       52519         491       66151      117567
Swap:         16383         624       15759
/opt/site/sge/default/spool/node736/job_scripts/2485121: line 14: nvidia-smi: command not found
2021-06-03 10:25:32.315620: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-06-03 10:25:52.109399: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-03 10:25:52.114493: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-06-03 10:25:52.114514: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-06-03 10:25:52.114538: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (node736.pri.csf3.alces.network): /proc/driver/nvidia/version does not exist
2021-06-03 10:25:52.114782: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-03 10:25:52.115969: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
2021-06-03 10:25:59.010640: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-06-03 10:25:59.011287: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2399835000 Hz
MODEL NAME = initial_test_step2
Epoch 1/10
2021-06-03 10:38:09.743037: W tensorflow/core/framework/op_kernel.cc:1751] Unknown: BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
Traceback (most recent call last):

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 891, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/mnt/jw01-aruk-home01/projects/ra_challenge/hestia/Hestia_imeche_vision_challenge/NN_recognition_train/dataset/secondary_generator.py", line 63, in secondary_generator
    X, enc_letter, enc_colour = generate_batch()

  File "/mnt/jw01-aruk-home01/projects/ra_challenge/hestia/Hestia_imeche_vision_challenge/NN_recognition_train/dataset/secondary_generator.py", line 43, in generate_batch
    for X, coords, letter, colour in executor.map(stitch_random_square, random.sample(list_of_grass_images,BATCH_SIZE)):

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception

concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.


Traceback (most recent call last):
  File "train_step2.py", line 24, in <module>
    train_this(model_name)
  File "/mnt/jw01-aruk-home01/projects/ra_challenge/hestia/Hestia_imeche_vision_challenge/NN_recognition_train/model/step_2.py", line 80, in train_this
    model.fit(tf_data, epochs = 10, verbose = 2, steps_per_epoch = 50, callbacks=[checkpoint])
  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 855, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError:  BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
Traceback (most recent call last):

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 891, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/mnt/jw01-aruk-home01/projects/ra_challenge/hestia/Hestia_imeche_vision_challenge/NN_recognition_train/dataset/secondary_generator.py", line 63, in secondary_generator
    X, enc_letter, enc_colour = generate_batch()

  File "/mnt/jw01-aruk-home01/projects/ra_challenge/hestia/Hestia_imeche_vision_challenge/NN_recognition_train/dataset/secondary_generator.py", line 43, in generate_batch
    for X, coords, letter, colour in executor.map(stitch_random_square, random.sample(list_of_grass_images,BATCH_SIZE)):

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()

  File "/mnt/jw01-aruk-home01/projects/psa_functional_genomics/differential_HiC_analyser/conda_env/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception

concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_30219]

Function call stack:
train_function

